export const personalUrls = [
  // Social Media
  'facebook.com',
  'instagram.com',
  'twitter.com',
  'tiktok.com',
  'snapchat.com',
  'linkedin.com',
  'reddit.com',
  'pinterest.com',
  'tumblr.com',
  'flickr.com',
  'whatsapp.com',
  'telegram.org',
  'wechat.com',
  'line.me',
  'viber.com',
  'discord.com',
  'clubhouse.com',
  'twitch.tv',
  'vk.com',
  'weibo.com',
  'quora.com',
  'medium.com',
  'meetup.com',
  'nextdoor.com',
  'myspace.com',
  'tagged.com',
  'ello.co',
  'caffeine.tv',
  'periscope.tv',
  'mastodon.social',

  // Dating
  'tinder.com',
  'bumble.com',
  'okcupid.com',
  'match.com',
  'eharmony.com',
  'plentyoffish.com',
  'hinge.co',
  'grindr.com',
  'adultfriendfinder.com',
  'ashleymadison.com',
  'zoosk.com',
  'christianmingle.com',
  'jdate.com',
  'coffeemeetsbagel.com',
  'happn.com',
  'badoo.com',
  'ourtime.com',
  'blackpeoplemeet.com',
  'elitesingles.com',
  'silversingles.com',
  'farmersonly.com',
  'clover.co',
  'her.app',
  'scruff.com',
  'taimi.com',
  'jswipe.com',
  'feeld.co',
  'muzmatch.com',
  'innerCircle.co',
  'theLeague.com',

  // Adult Content
  'pornhub.com',
  'xvideos.com',
  'xnxx.com',
  'redtube.com',
  'youporn.com',
  'tube8.com',
  'xhamster.com',
  'onlyfans.com',
  'fancentro.com',
  'cam4.com',
  'brazzers.com',
  'livejasmin.com',
  'stripchat.com',
  'bongacams.com',
  'chaturbate.com',
  'myfreecams.com',
  'adultempire.com',
  'adultdvdempire.com',
  'flirt4free.com',
  'streamate.com',
  'naughtyamerica.com',
  'realitykings.com',
  'bangbros.com',
  'digitalplayground.com',
  'mofos.com',
  'twistys.com',
  'adulttime.com',
  'kink.com',
  'manyvids.com',
  'clips4sale.com',

  // Streaming and video platforms
  'netflix.com',
  'hulu.com',
  'primevideo.com',
  'disneyplus.com',
  'hbomax.com',
  'peacocktv.com',
  'youtube.com',
  'dailymotion.com',
  'vimeo.com',
  'crunchyroll.com',
  'funimation.com',
  'tubitv.com',
  'pluto.tv',
  'vudu.com',
  'paramountplus.com',
  'appletv.apple.com',
  'curiositystream.com',
  'mubi.com',
  'criterion.com',
  'shudder.com',
  'britbox.com',
  'acorn.tv',
  'dramafever.com',
  'viki.com',
  'crackle.com',
  'imdb.tv',
  'popcornflix.com',
  'kanopy.com',
  'hoopla.com',

  // Private communication
  'whatsapp.com',
  'messenger.com',
  'telegram.org',
  'signal.org',
  'wechat.com',
  'line.me',
  'skype.com',
  'zoom.us',
  'discord.com',
  'viber.com',
  'threema.ch',
  'wire.com',
  'wickr.com',
  'keybase.io',
  'element.io',
  'session.org',
  'delta.chat',
  'jitsi.org',
  'whereby.com',
  'meet.google.com',
  'teams.microsoft.com',
  'slack.com',
  'rocketchat.com',
  'mattermost.com',
  'zulip.com',
  'riot.im',
  'tox.chat',
  'status.im',
  'matrix.org',

  // Forums and Community
  '4chan.org',
  '8kun.top',
  'somethingawful.com',
  'kiwifarms.net',
  'slashdot.org',
  'reddit.com',
  'voat.co',
  'gab.com',
  'parler.com',
  'minds.com',
  'steemit.com',
  'ruqqus.com',
  'saidit.net',
  'tildes.net',
  'hubski.com',
  'lemmy.ml',
  'raddle.me',
  'lobste.rs',
  'hacker.news',
  'metafilter.com',
  'fark.com',
  'digg.com',
  'newgrounds.com',
  'bodybuilding.com/forum',
  'resetera.com',

  // Health and wellness
  'webmd.com',
  'mayoclinic.org',
  'healthline.com',
  'medlineplus.gov',
  'nih.gov',
  'cdc.gov',
  'who.int',
  'everydayhealth.com',
  'medicalnewstoday.com',
  'verywellhealth.com',
  'drugs.com',
  'rxlist.com',
  'psychologytoday.com',
  'nhs.uk',
  'patient.info',
  'emedicinehealth.com',
  'health.com',
  'health.harvard.edu',
  'clevelandclinic.org',
  'hopkinsmedicine.org',
  'kidshealth.org',
  'familydoctor.org',
  'medscape.com',
  'netdoctor.co.uk',

  // Financial and Gambling
  'robinhood.com',
  'etrade.com',
  'bet365.com',
  'paddypower.com',
  'draftkings.com',
  'fanduel.com',
  'pokerstars.com',
  'coinbase.com',
  'binance.com',
  'kraken.com',
  'etoro.com',
  'tdameritrade.com',
  'fidelity.com',
  'vanguard.com',
  'schwab.com',
  'betfair.com',
  'williamhill.com',
  'bovada.lv',
  'bwin.com',
  '888.com',
  'unibet.com',
  'betway.com',
  'skybet.com',
  'ladbrokes.com',
  'coral.co.uk',
  'betfred.com',
  'partypoker.com',
  'fulltilt.com',

  // Shopping and Auction
  'ebay.com',
  'amazon.com',
  'aliexpress.com',
  'wish.com',
  'etsy.com',
  'walmart.com',
  'target.com',
  'bestbuy.com',
  'newegg.com',
  'overstock.com',
  'wayfair.com',
  'homedepot.com',
  'lowes.com',
  'macys.com',
  'nordstrom.com',
  'zappos.com',
  'asos.com',
  'shein.com',
  'jd.com',
  'rakuten.com',
  'bonanza.com',
  'shopify.com',
  'mercari.com',
  'poshmark.com',

  // Food Delivery
  'ubereats.com',
  'doordash.com',
  'grubhub.com',
  'postmates.com',
  'seamless.com',
  'deliveroo.com',
  'justeat.com',
  'foodpanda.com',
  'zomato.com',
  'swiggy.com',
  'wolt.com',
  'glovoapp.com',
  'rappi.com',
  'ifood.com.br',
  'talabat.com',
  'caviar.com',
  'waitr.com',
  'foodora.com',
  'delivery.com',
  'eatstreet.com',
  'chowbus.com',
  'gopuff.com',
  'instacart.com',
  'shipt.com',

  // Meme and humor sites
  '9gag.com',
  'memedroid.com',
  'funnyordie.com',
  'knowyourmeme.com',
  'cheezburger.com',
  'funnyjunk.com',
  'memecenter.com',
  'memebase.com',
  'ifunny.co',
  'hugelol.com',
  'memegenerator.net',
  'quickmeme.com',
  'imgflip.com',
  'ebaumsworld.com',
  'collegehumor.com',
  'theonion.com',
  'clickhole.com',
  'cracked.com',
  'thechive.com',
  'failblog.cheezburger.com',
  'somethingawful.com',
  'fark.com',
  'memeeconomy.com',

  // VPN and privacy
  'expressvpn.com',
  'nordvpn.com',
  'privateinternetaccess.com',
  'cyberghostvpn.com',
  'surfshark.com',
  'protonvpn.com',
  'mullvad.net',
  'torproject.org',
  'ipvanish.com',
  'hotspotshield.com',
  'tunnelbear.com',
  'windscribe.com',
  'vyprvpn.com',
  'purevpn.com',
  'strongvpn.com',
  'hidemyass.com',
  'privatevpn.com',
  'astrill.com',
  'safervpn.com',
  'zenmate.com',
  'perfectprivacy.com',
  'airvpn.org',
  'ivacy.com',
  'vpnunlimited.com',

  // File sharing
  'dropbox.com',
  'mega.nz',
  'wetransfer.com',
  'mediafire.com',
  'box.com',
  'google.com/drive',
  'onedrive.live.com',
  'icloud.com',
  'pcloud.com',
  'sync.com',
  'zippyshare.com',
  '4shared.com',
  'sendspace.com',
  'rapidshare.com',
  'uploaded.net',
  'filehosting.org',
  'files.fm',
  'transfernow.net',
  'send-anywhere.com',
  'filemail.com',
  'fromsmash.com',
  'sendgb.com',
  'myairbridge.com',
  'gofile.io',

  // Adult Dating and Hookup
  'fetlife.com',
  'kink.com',
  'alt.com',
  'collarspace.com',
  'seeking.com',
  'sugardaddy.com',
  'adultfriendfinder.com',
  'xmatch.com',
  'fling.com',
  'benaughty.com',
  'nostringsattached.com',
  'swinglifestyle.com',
  'swapfinder.com',
  'kasidie.com',
  'sdc.com',
  'fabswingers.com',
  'swingersheaven.com',
  'swingingheaven.co.uk',
  'adultmatchmaker.com',
  'redhotpie.com',
  'spicymatch.com',
  'swingersdate.club',
  'swingersboard.com',
  'swingular.com',

  // Drugs and psychedelics
  'erowid.org',
  'rollsafe.org',
  'psychonautwiki.org',
  'bluelight.org',
  'drugs-forum.com',
  'dmt-nexus.me',
  'shroomery.org',
  'tripsit.me',
  'dancesafe.org',
  'maps.org',
  'pillreports.net',
  'drugsdata.org',
  'psychedelicscience.org',
  'heffter.org',
  'beckleyfoundation.org',
  'drugsand.me',
  'psychedelictimes.com',
  'thethirdwave.co',
  'psychedelic.support',
  'psychedelicreview.com',
  'entheonation.com',
  'doubleblindmag.com',

  // Other potentially embarrassing or personal
  'furaffinity.net',
  'deviantart.com',
  'patreon.com',
  'chaturbate.com',
  'myfreecams.com',
  'e621.net',
  'inkbunny.net',
  'sofurry.com',
  'f-list.net',
  'e-hentai.org',
  'literotica.com',
  'asstr.org',
  'nifty.org',
  'lushstories.com',
  'fetishpapa.com',
  'bdsmsingles.com',
  'recon.com',
  'xtube.com',
  'clips4sale.com',
  'iwantclips.com',
  'manyvids.com',
  'onlyfans.com',
  'justfor.fans',
  'fansly.com',
]

export enum Roles {
  SUPERADMIN = 1,
  ADMIN = 2,
  EXTENSION_USER = 3,
}

export enum NotificationTypes {
  TODO_DUE_DATE_DETECTED = 'todo_due_date_detected',

  EMAIL_SCAN_ACCOUNT_STARTED = 'email_scan_account_started',
  EMAIL_STARTING_TO_SCAN = 'email_starting_to_scan',
  EMAIL_SCAN_ACCOUNT_FINISHED = 'email_scan_account_finished',
  EMAIL_ACCOUNT_NOT_FOUND = 'email_account_not_found',

  ACTIVITY_NEW_USER_ACTIVITIES_DETECTED = 'activity_new_user_activities_detected',
  ACTIVITY_NEW_VENDORS_DETECTED = 'activity_new_vendors_detected',
  ACTIVITY_SYNC_BROWSER_HISTORY_STARTED = 'activity_sync_browser_history_started',
  ACTIVITY_SYNC_BROWSER_HISTORY_FINISHED = 'activity_sync_browser_history_finished',
  ACTIVITY_NO_VENDORS_DETECTED = 'activity_no_vendors_detected',
  ACTIVITY_UPDATE_VENDORS_STARTED = 'activity_update_vendors_started',
  ACTIVITY_VENDORS_ADDED = 'activity_vendors_added',
}
